name: Unit Tests Main
on:
  pull_request:
    branches:
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@master
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com
      - name: Install node packages
        run: npm install
      - name: Run tests
        run: npm test
      - name: Run tests
        run: ls -a
      - name: Test Report coverage
        uses: romeovs/lcov-reporter-action@v0.2.11
        with:
          github-token: ${{ github.token }}
          lcov-file: coverage/lcov.info
          filter-changed-files: true